CREATE SCHEMA IF NOT EXISTS `tekila`;
USE `tekila`;
CREATE TABLE users (
	id INT(10) AUTO_INCREMENT NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY (id) );
